/**
 * Rule Registry — maps semantic rule IDs to known English rule text
 * and their effect (descriptionTrigger or projectRequirements).
 *
 * Each entry:
 *   id:          unique identifier used in code
 *   docType:     'OC' | 'ASN' | 'PO' | 'Invoice'
 *   effect:      'description' | 'projectReq' | 'both'
 *   englishText: canonical English text as shown in SBN transaction rules
 *   sub1:        subrule 1 text if applicable (optional)
 *   cxmlHint:    hint for which cXML element/attribute to look up
 */

const RULES = [
  // ─── OC — Project Requirements only ────────────────────────────────────
  {
    id: 'OC_FULL_CONFIRM_BEFORE_FULFILLMENT',
    docType: 'OC',
    effect: 'projectReq',
    englishText: 'Require suppliers to fully confirm line items before fulfillment',
    zh: '要求供应商完成前完全确认行项目。',
    ja: 'サプライヤは履行前に明細を完全に確認する必要がある',
    cxmlHint: null,
  },
  {
    id: 'OC_CONFIRM_BEFORE_ASN',
    docType: 'OC',
    effect: 'projectReq',
    englishText: 'Require suppliers to create an order confirmation before creating a ship notice',
    zh: '要求供应商在创建发货通知前创建订单确认。',
    ja: 'サプライヤは出荷通知の作成前にオーダー確認を作成する必要がある',
    cxmlHint: null,
  },
  {
    id: 'OC_ALLOW_UPDATE',
    docType: 'OC',
    effect: 'projectReq',
    triggerOnNo: true,
    englishText: 'Allow suppliers to confirm an order multiple times',
    projectReqText: 'OC Update is not allowed.',
    zh: '只允许进行一次订单确认。',
    ja: 'OC更新は許可されていません。',
    cxmlHint: null,
  },
  {
    id: 'OC_ALLOW_LINE_LEVEL',
    docType: 'OC',
    effect: 'projectReq',
    triggerOnBoth: true,
    englishText: 'Allow suppliers to send order confirmations for material orders at the line-item level',
    projectReqText: 'Header level/ Line level OC is allowed.',
    projectReqTextNo: 'Only header level OC is allowed.',
    zh: '支持抬头级及行项目级的订单确认。',
    zhNo: '仅允许确认整张订单。',
    ja: 'ヘッダーと明細レベルのオーダー確認をサポートされる。',
    jaNo: 'ヘッダーレベルのオーダー確認のみ許可される。',
    cxmlHint: null,
  },

  // ─── OC — B column description ──────────────────────────────────────────
  {
    id: 'OC_REQUIRE_DELIVERY_DATE',
    docType: 'OC',
    effect: 'description',
    englishText: 'Require delivery dates for order confirmations and ship notices',
    cxmlHint: 'ConfirmationStatus@deliveryDate',
  },
  {
    id: 'OC_REQUIRE_SHIP_DATE',
    docType: 'OC',
    effect: 'description',
    englishText: 'Require an estimated shipping date on order confirmations',
    cxmlHint: 'ConfirmationStatus@shipmentDate',
  },
  {
    id: 'OC_ALLOW_PARTIAL_REJECT',
    docType: 'OC',
    effect: 'projectReq',
    englishText: 'Allow suppliers to reject quantities for material orders at the line-item level in order confirmations',
    cxmlHint: null,
  },
  {
    id: 'OC_NO_REJECT_ENTIRE_PO',
    docType: 'OC',
    effect: 'description',
    englishText: 'Do not allow suppliers to reject entire purchase orders',
    cxmlHint: 'ConfirmationHeader/@type',
  },
  {
    id: 'OC_REQUIRE_REJECT_REASON_HEADER',
    docType: 'OC',
    effect: 'description',
    englishText: 'Require suppliers to provide a reason when they reject an order',
    cxmlHint: null,
  },
  {
    id: 'OC_REQUIRE_REJECT_REASON_LINE',
    docType: 'OC',
    effect: 'description',
    englishText: 'Require suppliers to provide a reason when they reject an order at the line-item level',
    cxmlHint: null,
  },
  {
    id: 'OC_REQUIRE_COMMENT_ON_CHANGE',
    docType: 'OC',
    effect: 'description',
    englishText: 'Require suppliers to enter a comment at the order confirmation line item level when there are any changes',
    cxmlHint: 'ConfirmationItem/Comments',
  },

  // ─── ASN — Project Requirements only ────────────────────────────────────
  {
    id: 'ASN_ALLOW_NON_PO',
    docType: 'ASN',
    effect: 'projectReq',
    triggerOnNo: true,
    englishText: 'Allow suppliers to send non-PO ship notices through cXML',
    projectReqTextNo: 'Non-PO ship notices via cXML are not allowed.',
    zh: '不允许通过cXML发送Non-PO发货通知。',
    ja: '注文書なし出荷通知の作成は許可されない。',
    cxmlHint: null,
  },
  {
    id: 'ASN_ALLOW_CANCEL',
    docType: 'ASN',
    effect: 'projectReq',
    englishText: 'Allow suppliers to cancel ship notices that they create',
    projectReqText: 'Suppliers are allowed to cancel ship notices.',
    cxmlHint: null,
  },
  {
    id: 'ASN_ALLOW_UPDATE',
    docType: 'ASN',
    effect: 'projectReq',
    englishText: 'Allow suppliers to edit existing ship notices',
    projectReqText: 'Suppliers are allowed to update ship notices.',
    cxmlHint: null,
  },
  {
    id: 'ASN_NO_MULTIPLE_DELIVERY_DATES',
    docType: 'ASN',
    effect: 'projectReq',
    englishText: 'Do not allow multiple delivery dates in ship notice creation',
    projectReqText: 'All items in the same ship notice must have the same delivery date.',
    zh: '同一发货通知中的所有行项目的希望交货期（requestedDeliveryDate）必须相同。',
    ja: '配達日時が同じ品目のみを出荷通知に含めることが許可される。',
    cxmlHint: null,
  },
  {
    id: 'ASN_NO_MULTIPLE_SHIPTO',
    docType: 'ASN',
    effect: 'projectReq',
    triggerOnBoth: true,
    englishText: 'Do not allow multiple Ship To addresses on a ship notice',
    projectReqText: 'Do not allow multiple Ship To addresses on a ship notice',
    projectReqTextNo: 'Allow multiple Ship To addresses on a ship notice.',
    zh: '不允许发货通知上具有多个送货地址。',
    zhNo: 'ASN中允许使用多个shipTo地址，默认情况下，shipTo在ASN中将被省略。',
    ja: '出荷通知で複数の出荷先住所を許可しない',
    jaNo: '複数の納入先住所を許可する。(=配送先が異なる、複数明細を含んだ出荷通知の作成を許可する。この場合、出荷通知内の配送先情報"ShipTo"は省略する形となる。)',
    cxmlHint: null,
  },

  // ─── Invoice — Project Requirements only ────────────────────────────────
  {
    id: 'INV_REQUIRE_OC_BEFORE_INVOICE',
    docType: 'Invoice',
    effect: 'projectReq',
    englishText: 'Require suppliers to create an order confirmation for the PO before creating an invoice',
    zh: '要求供应商创建发票之前为该 PO 创建订单确认。',
    ja: 'サプライヤは請求書の作成前に注文書に対するオーダー確認を作成する必要がある',
    cxmlHint: null,
  },
  {
    id: 'INV_REQUIRE_ASN_BEFORE_INVOICE',
    docType: 'Invoice',
    effect: 'projectReq',
    englishText: 'Require suppliers to create a ship notice for the PO before creating an invoice',
    zh: '要求供应商创建发票之前为该 PO 创建发货通知。',
    ja: 'サプライヤは請求書の作成前に注文書に対する出荷通知を作成する必要がある',
    cxmlHint: null,
  },
  {
    id: 'INV_SHIPPED_QTY_ONLY',
    docType: 'Invoice',
    effect: 'projectReq',
    englishText: 'Require suppliers to include only shipped quantities on invoices',
    zh: '要求供应商只包括发票上已发货的数量。',
    ja: 'サプライヤは請求書に出荷済み数量のみ含める必要がある',
    cxmlHint: null,
  },
  {
    id: 'INV_RECEIVED_QTY_ONLY',
    docType: 'Invoice',
    effect: 'projectReq',
    englishText: 'Require suppliers to include only received quantities on invoices',
    zh: '要求供应商只包括発票上已接收的数量。',
    ja: 'サプライヤは請求書に受入済み数量のみ含める必要がある',
    cxmlHint: null,
  },
  {
    id: 'INV_ALLOW_CANCEL',
    docType: 'Invoice',
    effect: 'projectReq',
    englishText: 'Allow suppliers to cancel invoices they create',
    projectReqText: "Suppliers are allowed to cancel invoices that do not have an invoice status of 'reconciled', 'paying', or 'paid'.",
    projectReqTextNo: 'Suppliers are not allowed to cancel invoices.',
    triggerOnBoth: true,
    cxmlHint: null,
  },
  {
    id: 'INV_DATE_NOT_BEFORE_ORDER',
    docType: 'Invoice',
    effect: 'projectReq',
    englishText: 'Require invoice date to not be before the order date',
    cxmlHint: null,
  },
  {
    id: 'INV_ALLOW_BACKDATING',
    docType: 'Invoice',
    effect: 'projectReq',
    englishText: 'Allow invoices to be back-dated the specified number of days',
    cxmlHint: null,
  },
  {
    id: 'INV_ALLOW_FUTUREDATING',
    docType: 'Invoice',
    effect: 'projectReq',
    englishText: 'Allow invoices to be future-dated the specified number of days',
    cxmlHint: null,
  },

  // ─── Invoice — B column description ────────────────────────────────────
  {
    id: 'INV_REQUIRE_CREDIT_MEMO_REASON',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide a reason for each credit memo',
    cxmlHint: 'InvoiceDetailRequestHeader/Comments',
  },
  {
    id: 'INV_REQUIRE_DELIVERY_NOTE_DATE',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to specify a delivery note date for each material item on an invoice',
    cxmlHint: 'IdReference@domain=deliveryNoteDate',
  },
  {
    id: 'INV_REQUIRE_SERVICE_DATES',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide start and end dates for each service item on an invoice',
    cxmlHint: 'InvoiceDetailServiceItem/Period@startDate@endDate',
  },
  {
    id: 'INV_REQUIRE_HEADER_SERVICE_DATES',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide start and end dates at header level on an invoice',
    cxmlHint: 'InvoiceDetailRequestHeader/Period@startDate@endDate',
  },
  {
    id: 'INV_REQUIRE_DATE_NOT_BEFORE_ORDER',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require invoice date to not be before the order date',
    cxmlHint: 'InvoiceDetailRequestHeader@invoiceDate',
  },
  {
    id: 'INV_REQUIRE_LINE_DESCRIPTION',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide line item descriptions',
    cxmlHint: [
      'InvoiceDetailItem/InvoiceDetailItemReference/Description',
      'InvoiceDetailServiceItem/InvoiceDetailServiceItemReference/Description',
    ],
  },
  {
    id: 'INV_REQUIRE_VALID_TAX_LIST',
    docType: 'Invoice',
    effect: 'both',
    englishText: 'Require suppliers to choose from your list of valid tax',
    cxmlHint: 'TaxDetail@category',
  },
  {
    id: 'INV_ALLOW_CUSTOM_TAX',
    docType: 'Invoice',
    effect: 'projectReq',
    englishText: 'Allow suppliers to create a tax rate and type for invoices and credit memos',
    projectReqText: 'Allow suppliers to create a tax rate and type for invoices and credit memos.',
    cxmlHint: null,
  },
  {
    id: 'INV_REQUIRE_SUPPLIER_TAX_ID',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide their tax ID on invoices',
    cxmlHint: 'InvoiceDetailRequestHeader/Extrinsic@name=supplierTaxID',
  },
  {
    id: 'INV_REQUIRE_TAX_AT_LINE',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to enter taxes at line item level',
    cxmlHint: 'InvoiceDetailItem/Tax',
  },
  {
    id: 'INV_REQUIRE_TAX_INFO',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide tax information in invoice',
    cxmlHint: 'Tax',
  },
  {
    id: 'INV_REQUIRE_VAT_INFO',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide VAT information in invoice headers or line items',
    cxmlHint: 'TaxDetail@category=vat',
  },
  {
    id: 'INV_REQUIRE_BILL_TO',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require a Bill To address on invoices',
    cxmlHint: 'InvoicePartner/Contact@role=billTo',
    extraHint: { type: 'invoicePartnerFor', role: 'billTo', label: 'Bill To' },
  },
  {
    id: 'INV_REQUIRE_SOLD_TO',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require a Sold To address on invoices',
    cxmlHint: 'InvoicePartner/Contact@role=soldTo',
    extraHint: { type: 'invoicePartnerFor', role: 'soldTo', label: 'Sold To' },
  },
  {
    id: 'INV_REQUIRE_FROM',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require a From address on invoices',
    cxmlHint: 'InvoicePartner/Contact@role=from',
    extraHint: { type: 'invoicePartnerFor', role: 'from', label: 'From' },
  },
  {
    id: 'INV_REQUIRE_REMIT_TO',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require a Remit To address on invoices',
    cxmlHint: 'InvoicePartner/Contact@role=remitTo',
    extraHint: { type: 'invoicePartnerFor', role: 'remitTo', label: 'Remit To' },
  },
  {
    id: 'INV_REQUIRE_BILL_FROM',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require a Bill From address on invoices (Japan only)',
    cxmlHint: 'InvoicePartner/Contact@role=billFrom',
    extraHint: { type: 'invoicePartnerFor', role: 'billFrom', label: 'Bill From' },
  },
  {
    id: 'INV_REQUIRE_SHIP_ADDRESSES',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require Ship From and Ship To addresses on invoices',
    cxmlHint: ['Contact@role=shipFrom', 'Contact@role=shipTo'],
    extraHint: { type: 'element', name: 'InvoiceDetailShipping', label: 'InvoiceDetailShipping element for ship from and ship to is mandatory' },
  },
  {
    id: 'INV_REQUIRE_PENALTY_TERMS',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide penalty information or terms on invoices',
    cxmlHint: 'InvoiceDetailRequestHeader/Extrinsic@name=penaltyInformation',
  },
  {
    id: 'INV_REQUIRE_DISCOUNT_TERMS',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide discount information or terms on invoices',
    cxmlHint: 'InvoiceDetailRequestHeader/PaymentTerm/Discount',
  },
  {
    id: 'INV_REQUIRE_NET_TERMS',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to provide net term information on the invoice',
    cxmlHint: 'InvoiceDetailRequestHeader/PaymentTerm@payInNumberOfDays',
    note: 'Applies to standard invoices only, not credit memos',
  },
  {
    id: 'INV_REQUIRE_BANK_ACCOUNT',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require suppliers to include bank account details on invoices',
    cxmlHint: 'InvoicePartner/Contact@role=wireReceivingBank',
  },
  {
    id: 'INV_REQUIRE_CUSTOMER_VAT_ID',
    docType: 'Invoice',
    effect: 'description',
    englishText: "Require customer's VAT/Tax ID",
    cxmlHint: 'InvoiceDetailRequestHeader/Extrinsic@name=buyerVatID',
    mergeGroup: 'BUYER_VAT_ID',
  },
  {
    id: 'INV_SHOW_DEFAULT_BUYER_VAT_ID',
    docType: 'Invoice',
    effect: 'description',
    englishText: "Show your company's default VAT ID",
    cxmlHint: 'InvoiceDetailRequestHeader/Extrinsic@name=buyerVatID',
    mergeGroup: 'BUYER_VAT_ID',
  },
  {
    id: 'INV_REQUIRE_BUYER_VAT_ID_INTRA_EU',
    docType: 'Invoice',
    effect: 'description',
    englishText: "Require your company's VAT ID only for intra-EU trade",
    cxmlHint: 'InvoiceDetailRequestHeader/Extrinsic@name=buyerVatID',
    mergeGroup: 'BUYER_VAT_ID',
  },
  {
    id: 'INV_REQUIRE_BUYER_VAT_ID_DOMESTIC',
    docType: 'Invoice',
    effect: 'description',
    englishText: "Require your company's VAT ID for domestic trade",
    cxmlHint: 'InvoiceDetailRequestHeader/Extrinsic@name=buyerVatID',
    mergeGroup: 'BUYER_VAT_ID',
  },
  {
    id: 'INV_REQUIRE_VAT_DETAILS_DOMESTIC_INTRA_EU',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require VAT details only for domestic and intra-EU trade',
    cxmlHint: 'TaxDetail@category=vat',
  },
  {
    id: 'INV_REQUIRE_SUPPLIER_VAT_ID',
    docType: 'Invoice',
    effect: 'description',
    englishText: "Require supplier's VAT/Tax ID",
    cxmlHint: 'InvoiceDetailRequestHeader/Extrinsic@name=supplierVatID',
  },
  {
    id: 'INV_REQUIRE_SUPPLY_DATE_FOR_VAT',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require supply date when VAT is chosen as tax category',
    cxmlHint: 'TaxDetail@category=vat@taxPointDate',
  },
  {
    id: 'INV_REQUIRE_TAX_IN_LOCAL_CURRENCY',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require tax amounts in local currency',
    cxmlHint: 'TaxDetail/TaxAmount@alternateAmount',
  },
  {
    id: 'INV_REQUIRE_TOTALS_IN_LOCAL_CURRENCY',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require subtotal and amount due in local currency',
    cxmlHint: 'InvoiceDetailSummary/SubtotalAmount/Money@alternateAmount@alternateCurrency',
  },
  {
    id: 'INV_REQUIRE_ZERO_VAT_EXPLANATION',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require explanation for zero rate VAT',
    cxmlHint: 'TaxDetail@category=vat@percentageRate=0@exemptDetail',
  },
  {
    id: 'INV_REQUIRE_ZERO_GST_EXPLANATION',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require explanation for zero rate GST',
    cxmlHint: 'TaxDetail@category=gst@percentageRate=0@exemptDetail',
  },
  {
    id: 'INV_REQUIRE_DETAILED_TAX_SUMMARY',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Require detailed tax information in tax summaries',
    cxmlHint: 'InvoiceDetailSummary/Tax/TaxDetail',
  },

  // ─── Invoice — special: NO triggers description ──────────────────────────
  {
    id: 'INV_PAYMENT_TERMS_MUST_MATCH_PO',
    docType: 'Invoice',
    effect: 'description',
    englishText: 'Allow suppliers to omit payment terms in PO invoices',
    triggerOnNo: true,
    cxmlHint: 'InvoiceDetailRequestHeader/PaymentTerm',
  },

  // ─── ASN — B column description ─────────────────────────────────────────
  {
    id: 'ASN_REQUIRE_DELIVERY_DATE',
    docType: 'ASN',
    effect: 'description',
    englishText: 'Require delivery dates for order confirmations and ship notices',
    cxmlHint: 'ShipNoticeHeader@deliveryDate',
  },
  {
    id: 'ASN_REQUIRE_SHIP_DATE',
    docType: 'ASN',
    effect: 'description',
    englishText: 'Require an actual or estimated shipping date on ship notices',
    cxmlHint: 'ShipNoticeHeader@shipmentDate',
  },
  {
    id: 'ASN_REQUIRE_SHIP_NOTICE_TYPE',
    docType: 'ASN',
    effect: 'description',
    englishText: 'Require ship notice type on ship notices',
    cxmlHint: 'ShipNoticeHeader@shipmentType',
  },
  {
    id: 'ASN_REQUIRE_PACKING_SLIP_UNIQUE',
    docType: 'ASN',
    effect: 'description',
    englishText: 'Require the Packing Slip ID to be unique on ship notices',
    cxmlHint: 'ShipNoticeHeader@shipmentID',
  },
];

function getRulesForDocType(docType) {
  return RULES.filter(r => r.docType === docType);
}

function getRuleById(id) {
  return RULES.find(r => r.id === id) || null;
}

module.exports = { RULES, getRulesForDocType, getRuleById };
